-- MySQL Script generated by MySQL Workbench
-- Sat Nov 14 23:09:05 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bancotcc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bancotcc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bancotcc` DEFAULT CHARACTER SET utf8 ;
USE `bancotcc` ;

-- -----------------------------------------------------
-- Table `bancotcc`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancotcc`.`cidade` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cidade` VARCHAR(70) NOT NULL,
  `estado` CHAR(2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancotcc`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancotcc`.`Cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `Cpf` CHAR(15) NOT NULL,
  `DataNascimento` DATE NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Senha` VARCHAR(65) NOT NULL,
  `Cep` CHAR(10) NOT NULL,
  `Endereco` VARCHAR(100) NOT NULL,
  `Complemento` VARCHAR(50) NOT NULL,
  `Bairro` VARCHAR(100) NOT NULL,
  `Telefone` CHAR(25) NOT NULL,
  `Celular` CHAR(25) NOT NULL,
  `Foto` VARCHAR(20) NOT NULL,
  `sexo` VARCHAR(25) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `numeroCasa` VARCHAR(15) NOT NULL,
  `numeroApto` VARCHAR(15) NULL,
  `cnpj` CHAR(20) NULL,
  `Ativo` ENUM('S', 'N') NOT NULL,
  `cidade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Cliente_Cidade1_idx` (`cidade_id` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC),
  CONSTRAINT `fk_Cliente_Cidade1`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `bancotcc`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancotcc`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancotcc`.`Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(100) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Login` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(20) NOT NULL,
  `Foto` VARCHAR(20) BINARY NOT NULL,
  `Ativo` ENUM('S', 'N') NOT NULL,
  `cidade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Usuario_Cidade1_idx` (`cidade_id` ASC),
  UNIQUE INDEX `Login_UNIQUE` (`Login` ASC),
  CONSTRAINT `fk_Usuario_Cidade1`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `bancotcc`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancotcc`.`departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancotcc`.`departamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `NomeDept` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `NomeDept_UNIQUE` (`NomeDept` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancotcc`.`Fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancotcc`.`Fornecedor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(50) NOT NULL,
  `Cnpj` CHAR(20) NOT NULL,
  `Telefone` CHAR(25) NOT NULL,
  `email` VARCHAR(100) NULL,
  `endereco` VARCHAR(100) NOT NULL,
  `cep` CHAR(15) NOT NULL,
  `Ativo` ENUM('S', 'N') NOT NULL,
  `Cidade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Fornecedor_Cidade1_idx` (`Cidade_id` ASC),
  CONSTRAINT `fk_Fornecedor_Cidade1`
    FOREIGN KEY (`Cidade_id`)
    REFERENCES `bancotcc`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancotcc`.`Transportadora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancotcc`.`Transportadora` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Cnpj` CHAR(20) NOT NULL,
  `Telefone` CHAR(20) NOT NULL,
  `Endereco` VARCHAR(45) NOT NULL,
  `cep` CHAR(15) NOT NULL,
  `email` VARCHAR(100) NULL,
  `Ativo` ENUM('S', 'N') NOT NULL,
  `cidade_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Transportadora_Cidade1_idx` (`cidade_id` ASC),
  CONSTRAINT `fk_Transportadora_Cidade1`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `bancotcc`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancotcc`.`tipopagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancotcc`.`tipopagamento` (
  `id` INT NOT NULL,
  `tipo_pagto` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancotcc`.`entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancotcc`.`entrega` (
  `id` INT NOT NULL,
  `previstoPara` DATE NULL,
  `cod_status` INT NOT NULL,
  `data_status` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancotcc`.`situacao_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancotcc`.`situacao_pedido` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancotcc`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancotcc`.`Pedido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `DataEmissao` DATE NOT NULL,
  `Historico_pedido` VARCHAR(100) NOT NULL,
  `valorTotal` DECIMAL NOT NULL,
  `enderecoCobranca` VARCHAR(100) NOT NULL,
  `enderecoEntrega` VARCHAR(100) NOT NULL,
  `quantidade` INT NOT NULL,
  `valorUnitario` DECIMAL NOT NULL,
  `desconto` DECIMAL NOT NULL,
  `Transportadora_id` INT NOT NULL,
  `tipopagamento_id` INT NOT NULL,
  `Cliente_id` INT NOT NULL,
  `entrega_id` INT NOT NULL,
  `situacao_pedido_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Pedido_Transportadora1_idx` (`Transportadora_id` ASC),
  INDEX `fk_Pedido_Cliente1_idx` (`Cliente_id` ASC),
  INDEX `fk_Pedido_tipopagamento1_idx` (`tipopagamento_id` ASC),
  INDEX `fk_Pedido_entrega1_idx` (`entrega_id` ASC),
  INDEX `fk_Pedido_situacao_pedido1_idx` (`situacao_pedido_id` ASC),
  CONSTRAINT `fk_Pedido_Transportadora1`
    FOREIGN KEY (`Transportadora_id`)
    REFERENCES `bancotcc`.`Transportadora` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`Cliente_id`)
    REFERENCES `bancotcc`.`Cliente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_tipopagamento1`
    FOREIGN KEY (`tipopagamento_id`)
    REFERENCES `bancotcc`.`tipopagamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_entrega1`
    FOREIGN KEY (`entrega_id`)
    REFERENCES `bancotcc`.`entrega` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_situacao_pedido1`
    FOREIGN KEY (`situacao_pedido_id`)
    REFERENCES `bancotcc`.`situacao_pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancotcc`.`Marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancotcc`.`Marca` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Marca` VARCHAR(45) NOT NULL,
  `logo` VARCHAR(20) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Marca_UNIQUE` (`Marca` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancotcc`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancotcc`.`Produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(50) NOT NULL,
  `ValorProduto` FLOAT NOT NULL,
  `Descricao` TEXT NOT NULL,
  `FotoProduto` VARCHAR(45) NOT NULL,
  `qtd_estoque` INT NOT NULL,
  `quantidade_minima_estoque` INT NOT NULL,
  `Marca_id` INT NOT NULL,
  `departamento_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Produto_Marca1_idx` (`Marca_id` ASC),
  INDEX `fk_Produto_departamento1_idx` (`departamento_id` ASC),
  CONSTRAINT `fk_Produto_Marca1`
    FOREIGN KEY (`Marca_id`)
    REFERENCES `bancotcc`.`Marca` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_departamento1`
    FOREIGN KEY (`departamento_id`)
    REFERENCES `bancotcc`.`departamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancotcc`.`Item_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancotcc`.`Item_pedido` (
  `id` INT NOT NULL,
  `Pedido_id` INT NOT NULL,
  `Produto_id` INT NOT NULL,
  `quantidade` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Pedido_has_Produto_Produto1_idx` (`Produto_id` ASC),
  INDEX `fk_Pedido_has_Produto_Pedido_idx` (`Pedido_id` ASC),
  CONSTRAINT `fk_Pedido_has_Produto_Pedido`
    FOREIGN KEY (`Pedido_id`)
    REFERENCES `bancotcc`.`Pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_has_Produto_Produto1`
    FOREIGN KEY (`Produto_id`)
    REFERENCES `bancotcc`.`Produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancotcc`.`FornecedorProduto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancotcc`.`FornecedorProduto` (
  `id` INT NOT NULL,
  `Produto_id` INT NOT NULL,
  `Fornecedor_id` INT NOT NULL,
  `Estoque` INT NOT NULL,
  `DescricaoProduto` VARCHAR(100) NOT NULL,
  INDEX `fk_Produto_has_Fornecedor_Fornecedor1_idx` (`Fornecedor_id` ASC),
  INDEX `fk_Produto_has_Fornecedor_Produto1_idx` (`Produto_id` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Produto_has_Fornecedor_Produto1`
    FOREIGN KEY (`Produto_id`)
    REFERENCES `bancotcc`.`Produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Produto_has_Fornecedor_Fornecedor1`
    FOREIGN KEY (`Fornecedor_id`)
    REFERENCES `bancotcc`.`Fornecedor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancotcc`.`status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancotcc`.`status` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancotcc`.`rastreio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancotcc`.`rastreio` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(60) NOT NULL,
  `data_status` TIMESTAMP NOT NULL,
  `geo_lat` VARCHAR(15) NULL,
  `geo_long` VARCHAR(15) NULL,
  `status_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_rastreio_status1_idx` (`status_id` ASC),
  CONSTRAINT `fk_rastreio_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `bancotcc`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancotcc`.`PedidoRastreio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancotcc`.`PedidoRastreio` (
  `Pedido_id` INT NOT NULL,
  `rastreio_id` INT NOT NULL,
  `id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Pedido_has_rastreio_rastreio1_idx` (`rastreio_id` ASC),
  INDEX `fk_Pedido_has_rastreio_Pedido1_idx` (`Pedido_id` ASC),
  CONSTRAINT `fk_Pedido_has_rastreio_Pedido1`
    FOREIGN KEY (`Pedido_id`)
    REFERENCES `bancotcc`.`Pedido` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_has_rastreio_rastreio1`
    FOREIGN KEY (`rastreio_id`)
    REFERENCES `bancotcc`.`rastreio` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancotcc`.`produto_saldo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancotcc`.`produto_saldo` (
  `id` INT NOT NULL,
  `qtd_disponivel` INT NOT NULL,
  `qtd_receber` INT NOT NULL,
  `Produto_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_produto_saldo_Produto1_idx` (`Produto_id` ASC),
  CONSTRAINT `fk_produto_saldo_Produto1`
    FOREIGN KEY (`Produto_id`)
    REFERENCES `bancotcc`.`Produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancotcc`.`tipo_movimentacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancotcc`.`tipo_movimentacao` (
  `id` INT NOT NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bancotcc`.`movimentacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bancotcc`.`movimentacao` (
  `id` INT NOT NULL,
  `data_movimentacao` VARCHAR(45) NULL,
  `Produto_id` INT NOT NULL,
  `tipo_movimentacao_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_movimentacao_Produto1_idx` (`Produto_id` ASC),
  INDEX `fk_movimentacao_tipo_movimentacao1_idx` (`tipo_movimentacao_id` ASC),
  CONSTRAINT `fk_movimentacao_Produto1`
    FOREIGN KEY (`Produto_id`)
    REFERENCES `bancotcc`.`Produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_movimentacao_tipo_movimentacao1`
    FOREIGN KEY (`tipo_movimentacao_id`)
    REFERENCES `bancotcc`.`tipo_movimentacao` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
